export interface Screenshot {
  id: string; // Unique identifier, typically the file name
  uri: string; // The native filesystem URI for the original file
  webPath: string; // A web-accessible path for the <img> src attribute, generated by Capacitor
  description: string;
  name: string;
  creationTime: number; // Unix timestamp (milliseconds)
}