import type { ExtractedEntities } from './onDeviceAiPlugin';

export interface Screenshot {
  id: string; // Unique identifier, typically the file name
  uri: string; // The native filesystem URI for the original file
  webPath: string; // A web-accessible path for the <img> src attribute, generated by Capacitor
  thumbnailWebPath?: string; // An optional web-accessible path for a smaller, optimized thumbnail
  description: string;
  name: string;
  creationTime: number; // Unix timestamp (milliseconds)

  // V2 - Rich AI Analysis Fields (optional for backward compatibility)
  text?: string | null;
  entities?: ExtractedEntities | null;
  category?: string | null;
}

/**
 * Represents a Screenshot that has successfully undergone AI analysis.
 * The optional fields from the base Screenshot type are now mandatory.
 */
export interface AnalyzedScreenshot extends Screenshot {
  text: string;
  entities: ExtractedEntities;
  category: string;
}

/**
 * A TypeScript type guard to check if a screenshot has been analyzed.
 * @param screenshot The screenshot object to check.
 * @returns `true` if the screenshot has valid text and entities, `false` otherwise.
 */
export function isAnalyzed(screenshot: Screenshot): screenshot is AnalyzedScreenshot {
    return screenshot.text != null && screenshot.entities != null && screenshot.category != null;
}
